pipeline {
    agent any
    tools {
        maven 'Maven 3.8.1' // Defined in Jenkins -> Global Tool Configuration
        jdk 'JDK 11'         // Also defined in Jenkins global settings
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/ReshmithaThappeta/java-maven-app.git'
            }
        }
        stage('Debug Workspace') {
    steps {
        sh 'pwd'      // Should show the full path ending with java-maven-app/src
        sh 'ls -la'   // Should list pom.xml and Jenkinsfile here
    	sh 'ls -la src'
           }
	}
        stage('Build') {
            steps {
                  dir('java-maven-app/src') {
		    sh 'mvn clean install'
            }
          }
	}

	stage('Test') {
   		 steps {
       		     dir('java-maven-app') {
          	      sh 'mvn test'
          }
    	 }
	}

        stage('Package') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }
}

